version: "3.8"

services:
  mariadb:
    build: ./mariadb
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: devsecops
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin_password
    expose:
      - "40000"
    ports:
      - "40000:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./mariadb:/docker-entrypoint-initdb.d
      - ./mariadb/encryption.cnf:/etc/mysql/conf.d/encryption.cnf
      - ./mariadb/compress.cnf:/etc/mysql/conf.d/compress.cnf
      - ./mariadb/keys.enc:/etc/mysql/conf.d/keys.enc
    networks:
      backend:

  phpmyadmin:
    image: phpmyadmin
    restart: always
    expose:
      - "40001"
    ports:
      - "40001:80"
    environment:
      - PMA_HOST=mariadb
      - PMA_PORT=3306
    networks:
      backend:

  nodejs1:
    build: ./back
    restart: always
    expose:
      - "40002"
    ports:
      - "40002:3000"
    depends_on:
      mariadb:
        condition: service_started
    networks:
      backend:

  nodejs2:
    build: ./back
    restart: always
    expose:
      - "40003"
    ports:
      - "40003:3000"
    depends_on:
      mariadb:
        condition: service_started
    networks:
      backend:

  nginx:
    build:
      context: ./Nginx
    ports:
      - "40004:80"
      - "443:443"
    volumes:
      - ./Nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./Nginx/certs:/etc/nginx/certs
    depends_on:
      - nodejs1
      - nodejs2
    networks:
      backend:

networks:
  backend:

volumes:
  db_data:
