GRANT ALL PRIVILEGES ON *.* TO 'admin'@'%' WITH GRANT OPTION;
FLUSH PRIVILEGES;

CREATE USER 'app_user'@'%' IDENTIFIED BY 'app_password';
GRANT ALTER, CREATE, SELECT, INSERT, UPDATE, DELETE ON `devsecops`.* TO 'app_user'@'%';
FLUSH PRIVILEGES;
